version: '2'  
services:  
  nginx:
    image: nginx:latest
    container_name: nz01
    ports:
      - "8000:8000"
    volumes:
      - ./src:/src
      - ./config/nginx:/etc/nginx/conf.d
      - /static:/static
    depends_on:
      - web
  web:
    build: .
    container_name: dz01
    command: bash -c 'python manage.py makemigrations && python manage.py migrate && gunicorn mydjango.wsgi -g 0.0.0.0:8000'
    depends_on:
      - db
    volumes:
      - ./src:/src
      - /static:/static
    expose:
      - "8000"
    links:
      - redis

  db:
    image: postgres:latest
    container_name: pz01

  redis:
    image: redis:latest
    container_name: rz01
    ports:
     - '6379:6379'

  celery:
    build: .
    container_name: cz01
    command: celery worker --app=utility.tasks
    volumes:
      - ..:/src
    links:
      - db
      - redis
